### ISSUE TITLE
Unable to process controversial videos

### ISSUE THREAD

**Issue by fastrocket** [Tyrrrz/YoutubeExplode#101]
As an example, this political parody Youtube link has restricted content that requires confirmation: (may be offensive or inappropriate for some viewers)

https://www.youtube.com/watch?v=BRi-UouACL8

Once you agree, you get this URL:

https://www.youtube.com/watch?v=BRi-UouACL8&bpctr=1522215065

With either URL in the DemoWpf program, I get this exception:

YoutubeExplode.Exceptions.VideoUnavailableException
  HResult=0x80131500
  Source=YoutubeExplode
  StackTrace:
   at YoutubeExplode.YoutubeClient.<GetVideoInfoAsync>d__35.MoveNext() in C:\Code\YoutubeExplode\YoutubeExplode\YoutubeClient.Video.cs:line 82
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at YoutubeExplode.YoutubeClient.<GetVideoAsync>d__38.MoveNext() in C:\Code\YoutubeExplode\YoutubeExplode\YoutubeClient.Video.cs:line 206
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at DemoWpf.ViewModels.MainViewModel.<GetData>d__45.MoveNext() in C:\Code\YoutubeExplode\DemoWpf\ViewModels\MainViewModel.cs:line 138

**Comment by Tyrrrz** [comment]
Huh, this is interesting, never seen this video type before. It looks like that `bpctr` thing is generated uniquely for each session but it doesn't directly appear in the page source.

**Comment by Tyrrrz** [comment]
Looks like `bpctr=9999999999` works every time but only on the watch page.

**Comment by TEDSON007** [comment]
The link does not require any confirmation for me, even logged out.
Any more examples?

**Comment by Tyrrrz** [comment]
Try incognito

**Comment by TEDSON007** [comment]
Plays without issue or prompt.

**Comment by Tyrrrz** [comment]
Ah yeah, it looks like the video in original post is no longer restricted.

**Comment by WhiteLionATX** [comment]
Maybe double posted (sorry if so): 
https://github.com/Tyrrrz/YoutubeExplode/issues/110

**Comment by megakook** [comment]
Here I found another example video
https://www.youtube.com/watch?v=SNPNWEY44NY
Need to look for da joos did 9/11 videos or da Holohoax. Anything bad for Israel gets flagged by the joo army of snot nosed teenagers in Tel Aviv working for the Hasbara hoping for Mossad career.

**Comment by megakook** [comment]
Whereas this one is flagged but doesn't have the bpctr addon after agreed entry

https://www.youtube.com/watch?v=_LGOd4xWAtI

And now a few days later it does. This suggests human processing. They are reclassifying. 
https://www.youtube.com/watch?v=_LGOd4xWAtI&bpctr=1525165829

One thing is for sure, all of it, all the motivation is one thing and one thing only: The road to Zion

**Comment by Tyrrrz** [comment]
But have you checked if it affects restricted videos?

**Comment by Tyrrrz** [comment]
None of them work with `get_video_info`, the `bpctr=9999999999` trick works with watch page which we currently do not parse for video info...

**Comment by knightking100** [comment]
Why not parse video info from the web page?

**Comment by Xetaxheb** [comment]
https://www.youtube.com/watch?v=NgTdNd5lkvY here's an example if you need one
