### ISSUE TITLE
This video is not available.

### ISSUE THREAD

**Issue by tuanbs** [Tyrrrz/YoutubeExplode#155]
I'm using the latest version 4.3.3 and got the error message: `Video [KOOtkK1F734] is not available and cannot be processed. Code: 150. Reason: This video is not available..`. Its Youtube url is: `https://www.youtube.com/watch?v=KOOtkK1F734`.

Details:
```bash
at YoutubeExplode.YoutubeClient.<GetVideoInfoAsync>d__35.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at YoutubeExplode.YoutubeClient.<GetVideoAsync>d__38.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Web.Controllers.WebApi.FilesController.<GetYoutubeInfoByYoutubeVideoUrl>d__8.MoveNext() in
```

Thanks in advance for any help. Cheers.

**Comment by SlowLogicBoy** [comment]
Well you can't get unavailable videos form youtube.

**Comment by Tyrrrz** [comment]
I would be more curious what is it that Youtube-dl is doing that lets it download unavailable videos

**Comment by tuanbs** [comment]
> I would be more curious what is it that Youtube-dl is doing that lets it download unavailable videos

Hi, I mean the video is available from this url: `https://www.youtube.com/watch?v=KOOtkK1F734` and I'm able to download it using youtube-dl. But YoutubeExplode cannot download it.

**Comment by shaked6540** [comment]
I'm getting video unavailable too, it is probably region locked

**Comment by shaked6540** [comment]
just to confirm, youtube-dl cant download it either: https://image.prntscr.com/image/hUSlVy6fTIinLksIcfaN1A.png

**Comment by tuanbs** [comment]
> just to confirm, youtube-dl cant download it either: https://image.prntscr.com/image/hUSlVy6fTIinLksIcfaN1A.png

I can download it:
<img width="791" alt="screenshot 2018-10-06 09 33 35" src="https://user-images.githubusercontent.com/4801395/46564504-16613680-c94b-11e8-8c16-bc18d264fdba.png">

**Comment by Giggitybyte** [comment]
[Works on my machine.](https://ihate.space/EDC1mga.png)

**Comment by Giggitybyte** [comment]
I also believe it is totally possible to get the reason for unavailability. There are websites out there that allow you to check if a video is region locked, so I don't see why YoutubeExplode couldn't do that too. I'd imagine there'd also be ways to parse the page and figure out if a video is age restricted, copyright claimed, etc.

**Comment by smartbracker** [comment]
YoutubeExplode working here this video  `https://www.youtube.com/watch?v=KOOtkK1F734`

**Comment by Tyrrrz** [comment]
I think this is indeed country block and YtDl is doing something to circumvent it, probably. Although it's weird that it still failed for @shaked6540

**Comment by smartbracker** [comment]
I'm not sure and I did not stop to study. 

Seens youtube-dl use a common **User-Agent**
`Mozilla/5.0 (X11; Linux x86_64; rv:59.0) Gecko/20100101 Firefox/59.0`
YoutubeExplode use exclusive  **User-Agent**.
`YoutubeExplode (github.com/Tyrrrz/YoutubeExplode)`

If someone is wrong, **this video is not available**, want try change User-Agent header.

Maybe it will not change anything, but it does not hurt to try.

**Comment by shaked6540** [comment]
I just tried that, same error
I think its blocking by IP and not user agent

**Comment by Tyrrrz** [comment]
I can't download with yt-dl either.
![image](https://user-images.githubusercontent.com/1935960/46631643-b2a85a80-cb50-11e8-9b87-a53da118b2cf.png)

**Comment by Tyrrrz** [comment]
It looks like it's in fact not country blocked, at least for me.

**Comment by tuanbs** [comment]
Today I got another error message:
`Additional text encountered after finished reading JSON content: }. Path '', line 1, position 15048.`

Details:
```bash
at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.Linq.JToken.Parse(String json, JsonLoadSettings settings)
   at YoutubeExplode.YoutubeClient.<GetVideoEmbedPageConfigAsync>d__31.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at YoutubeExplode.YoutubeClient.<GetVideoPlayerContextAsync>d__36.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at YoutubeExplode.YoutubeClient.<GetVideoMediaStreamInfosAsync>d__40.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Web.Controllers.WebApi.FilesController.<GetYoutubeInfoByYoutubeVideoUrl>d__8.MoveNext() in 
```

There were just some of videos in my website got this error when I posted this issue. But now all of videos have this error. Any help or idea would be much appreciated. Thanks in advance.

**Comment by SlowLogicBoy** [comment]
@tuanbs this is a different issue #164 is what you are looking for.
