### ISSUE TITLE
Cannot download some videos

### ISSUE THREAD

**Issue by zjjohncq** [Tyrrrz/YoutubeExplode#237]
I have some videos was not able to download. All packages is in latest version. I have recorded the following exception:
Exception download https://www.youtube.com/watch?v=D9lnO3HK11o at May 13, 2019 9:36:38 PM
System.IO.IOException: Received an unexpected EOF or 0 bytes from the transport stream.
   at System.Net.ConnectStream.EndRead(IAsyncResult asyncResult)
   at System.IO.Stream.<>c.<BeginEndReadAsync>b__43_1(Stream stream, IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrimPromise`1.Complete(TInstance thisRef, Func`3 endMethod, IAsyncResult asyncResult, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClientHandler.WebExceptionWrapperStream.<ReadAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at YoutubeExplode.Internal.SegmentedHttpStream.<ReadAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at YoutubeExplode.Internal.Extensions.<CopyToAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at YoutubeExplode.YoutubeClient.<DownloadMediaStreamAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at YoutubeExplode.YoutubeClient.<DownloadMediaStreamAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at YoutubeDownloader.AsyncHelper.RunSync(Func`1 func) in C:\Applications\Youtube\YoutubeExplode-master\YoutubeExplode-master\YoutubeDownloader\AsyncHelper.cs:line 39
   at YoutubeDownloader.Form1.DownloadYTBFile(String title, String url) in C:\Applications\Youtube\YoutubeExplode-master\YoutubeExplode-master\YoutubeDownloader\Form1.cs:line 295
   at YoutubeDownloader.Form1.Downloading(String sourceFile) in C:\Applications\Youtube\YoutubeExplode-master\YoutubeExplode-master\YoutubeDownloader\Form1.cs:line 189
Exception download https://www.youtube.com/watch?v=KEDz4o8Z1_Q at May 13, 2019 9:36:49 PM
System.IO.IOException: Received an unexpected EOF or 0 bytes from the transport stream.
   at System.Net.ConnectStream.EndRead(IAsyncResult asyncResult)
   at System.IO.Stream.<>c.<BeginEndReadAsync>b__43_1(Stream stream, IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrimPromise`1.Complete(TInstance thisRef, Func`3 endMethod, IAsyncResult asyncResult, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClientHandler.WebExceptionWrapperStream.<ReadAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at YoutubeExplode.Internal.SegmentedHttpStream.<ReadAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at YoutubeExplode.Internal.Extensions.<CopyToAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at YoutubeExplode.YoutubeClient.<DownloadMediaStreamAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at YoutubeExplode.YoutubeClient.<DownloadMediaStreamAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at YoutubeDownloader.AsyncHelper.RunSync(Func`1 func) in C:\Applications\Youtube\YoutubeExplode-master\YoutubeExplode-master\YoutubeDownloader\AsyncHelper.cs:line 39
   at YoutubeDownloader.Form1.DownloadYTBFile(String title, String url) in C:\Applications\Youtube\YoutubeExplode-master\YoutubeExplode-master\YoutubeDownloader\Form1.cs:line 295
   at YoutubeDownloader.Form1.Downloading(String sourceFile) in C:\Applications\Youtube\YoutubeExplode-master\YoutubeExplode-master\YoutubeDownloader\Form1.cs:line 189

**Comment by Tyrrrz** [comment]
Yes, unfortunately looks like the streams are broken. There's nothing we can do about it.
Seems like the same problem as in #219

**Comment by zjjohncq** [comment]
Thanks,  the quality loop works.
