### ISSUE TITLE
YouTubeExplode.Exceptions.UnexpectedIdentifierException

### ISSUE THREAD

**Issue by ddz95** [Tyrrrz/YoutubeExplode#24]
```
YoutubeExplode.Exceptions.UnexpectedIdentifierException occurred
  HResult=0x80131500
  Message=Unexpected itag [139]
  Source=YoutubeExplode
  StackTrace:
   at YoutubeExplode.Models.MediaStreams.MediaStreamInfo.GetContainer(Int32 itag)
   at YoutubeExplode.Models.MediaStreams.MediaStreamInfo..ctor(Int32 itag, String url, Int64 contentLength)
   at YoutubeExplode.Models.MediaStreams.AudioStreamInfo..ctor(Int32 itag, String url, Int64 contentLength, Int64 bitrate)
   at YoutubeExplode.YoutubeClient.<GetVideoInfoAsync>d__7.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PLAYER.MainWindow.<>c__DisplayClass127_0.<<GetURLS>b__0>d.MoveNext() in C:\Users\Dawid\Desktop\PLAYER\PLAYER\MainWindow.xaml.cs:line 2080
```

Line that called it:

```
var videoInfo = await client.GetVideoInfoAsync(currentLink);
Content of currentLink:
currentLink	"NnPKBwO4-P8"	string
```

It worked today. Now I have no idea what's causing the problem :/ Any ideas?

**Comment by Tyrrrz** [comment]
Looks like Youtube added more itags. I'll add handles for them.

**Comment by ddz95** [comment]
What are those itags?

**Comment by Tyrrrz** [comment]
Identifiers for media streams, they describe what kind of content is inside of it.

**Comment by Tyrrrz** [comment]
Update your nuget package

**Comment by ddz95** [comment]
Done, thanks. Great job with this library btw.

**Comment by SlowLogicBoy** [comment]
Oh wow this was fast! thanks.

**Comment by Tyrrrz** [comment]
Shouldn't happen again. Unknown itags are now skipped in the release build.
