### ISSUE TITLE
Could not find signature decipherer function name

### ISSUE THREAD

**Issue by luca233** [Tyrrrz/YoutubeExplode#254]
Could not find signature decipherer function name.

**Comment by wleader** [comment]
Just saw the same thing, Multiple different videos. 

   at YoutubeExplode.YoutubeClient.<GetCipherOperationsAsync>d__40.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at YoutubeExplode.YoutubeClient.<GetVideoMediaStreamInfosAsync>d__43.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()

**Comment by wleader** [comment]
Oh, this is a duplicate of #252

**Comment by Tyrrrz** [comment]
Duplicate of #252
