### ISSUE TITLE
GetVideoMediaStreamInfosAsync Gets 403 Forbidden

### ISSUE THREAD

**Issue by wleader** [Tyrrrz/YoutubeExplode#285]
I'm getting an exception when calling GetVideoMediaStreamInfosAsync with code that was working. Perhaps Youtube changed something?

Video ID wn35LMzM8ro

My stack trace:

System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at YoutubeExplode.Internal.HttpClientEx.<GetStreamAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at YoutubeExplode.Internal.SegmentedHttpStream.<ReadAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at YoutubeExplode.Internal.Extensions.<CopyToAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at YoutubeExplode.YoutubeClient.<DownloadMediaStreamAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at YoutubeExplode.YoutubeClient.<DownloadMediaStreamAsync>d__15.MoveNext()

**Comment by vladimirplancak** [comment]
I'm experiencing the same issue, it was working previously, like 8 - 12 hours ago.

**Comment by acosano** [comment]
Not really sure if is the same error but I just got "Response status does not indicate success: 403 (For bidden)"

Video ID PmYypVozQb4

**Comment by DominicMaas** [comment]
Another day, another YouTube API change... Anyone able to take a deeper look at the moment? I'm currently a little busy.

**Comment by omansak** [comment]
probably this time is not "Decrypt Regex" issue

**Comment by shaked6540** [comment]
It happens on all age restricted videos I checked

**Comment by omansak** [comment]
> It happens on all age restricted videos I checked

i dont sure

**Comment by Hanzalah-Adalan** [comment]
It was failing for few hours, I noticed that too.. but now it's working again like usual.. not sure what's going on..

**Comment by DominicMaas** [comment]
Can confirm on my end as well, started working again.

**Comment by jmbits** [comment]
Still not working for me. I tried one of the urls from muxed, and I get 403.

**Comment by wleader** [comment]
Worked for me just now.

**Comment by Tyrrrz** [comment]
I like it when issues get fixed on their own :)
