### ISSUE TITLE
403 on age restricted videos

### ISSUE THREAD

**Issue by shaked6540** [Tyrrrz/YoutubeExplode#287]
Trying to download age-restricted videos returns 403 (forbidden)

stacktrace: 
```
System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at YoutubeExplode.Internal.HttpClientEx.<GetStreamAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at YoutubeExplode.Internal.SegmentedHttpStream.<ReadAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at YoutubeExplode.Internal.Extensions.<CopyToAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at YoutubeExplode.YoutubeClient.<DownloadMediaStreamAsync>d__14.MoveNext()
```

example video: https://www.youtube.com/watch?v=hSbBf4REAA8

seems like it happened in the past too, #65 and #110

**Comment by Tyrrrz** [comment]
Still happening in 4.7.9?

**Comment by shaked6540** [comment]
nope, it works now

**Comment by Tyrrrz** [comment]
Awesome
