### ISSUE TITLE
Roughly half of the videos in a playlist return 403 (forbidden).

### ISSUE THREAD

**Issue by Kajirinn** [Tyrrrz/YoutubeExplode#311]
I take it youtube has updated something or I somehow messed up my code, but half of the videos in my test playlist seem to be forbidden.

```
Exception thrown: 'System.Net.Http.HttpRequestException' in mscorlib.dll
System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at YoutubeExplode.Internal.HttpClientEx.<GetStreamAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at YoutubeExplode.Internal.SegmentedHttpStream.<ReadAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at YoutubeExplode.Internal.Extensions.<CopyToAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at YoutubeExplode.YoutubeClient.<DownloadMediaStreamAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at YoutubeExplode.YoutubeClient.<DownloadMediaStreamAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at DownloadHelper.<>c__DisplayClass5_0.<<Download>b__0>d.MoveNext() in
```

[The playlist in question.](https://www.youtube.com/playlist?list=PL1Gv-OC8tneodd99wZvmJFm4qs6ABOHIQ)

**Comment by Kajirinn** [comment]
Edit; I forgot to mention this happens when I attempt to download them with `DownloadMediaStreamAsync`.

**Comment by Kajirinn** [comment]
The issue seems to be resolved, not sure what youtube is doing.

On a different note, thank you for always keeping this project alive; you're the reason most of my projects work. I'll be sure to check out your patreon!

**Comment by Tyrrrz** [comment]
Great :)

**Comment by Tyrrrz** [comment]
Closing until next incident
