### ISSUE TITLE
Error in SearchVideosAsync

### ISSUE THREAD

**Issue by isjsg97** [Tyrrrz/YoutubeExplode#315]
When I ask any questions, the following error returns:
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
at Newtonsoft.Json.JsonTextReader.ParseValue()
at Newtonsoft.Json.Linq.JToken.ReadFrom(JsonReader reader, JsonLoadSettings settings)
at Newtonsoft.Json.Linq.JToken.Parse(String json, JsonLoadSettings settings)
at YoutubeExplode.YoutubeClient.GetSearchResultsJsonAsync(String query, Int32 page)
at YoutubeExplode.YoutubeClient.SearchVideosAsync(String query, Int32 maxPages)

**Comment by isjsg97** [comment]
Hi, 
Here I leave a few test cases in which I get the error.

Snoop Dogg - Lodi Dodi (feat. Nancy Fletcher)
Aphex Twin - Schottkey 7th Path
ZZ Top - Gimme All Your Lovin'
Avril Lavigne - What the Hell
Mägo de Oz - Molinos De Viento
Jerry Garcia - Shady Grove

**Comment by Tyrrrz** [comment]
Looks like it's not related to a particular search. The parsing fails because YouTube responds with an HTML that basically says "you've made too many suspicious requests, solve this captcha or wait". I don't think there's much to do here but we can wrap exceptions like this into something like `TransientException` so you can set up a Polly policy to retry.
