### ISSUE TITLE
GetChannelId method allows to use only English characters

### ISSUE THREAD

**Issue by Geckon01** [Tyrrrz/YoutubeExplode#346]
I've tried to use SearchChannelId method and I'm getting an"Invalid YouTube username"  exception while using cyrillic characters in actual username. I've checked the channel name with ValidateUsername and always get false with non english characters. 

Stack trace:
```
   at YoutubeExplode.YoutubeClient.<GetChannelIdAsync>d__2.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at DiscordNewsBot.Clients.YouTubeClient.<SearchChannelId>d__9.MoveNext() in C:\Users\Geckon01\source\repos\DiscrodNewsBot\DiscrodNewsBot\Clients\YouTubeClient.cs:line 67
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at DiscordNewBot.Commands.MainCommands.<AddChannel>d__4.MoveNext() in C:\Users\Geckon01\source\repos\DiscrodNewsBot\DiscrodNewsBot\Commands\MainCommands.cs:line 64
```

**Comment by Tyrrrz** [comment]
Can you please link the channel in question?

**Comment by Geckon01** [comment]
> Can you please link the channel in question?

The channel from question: https://www.youtube.com/channel/UCa6NgJFUoYtZB4PTcCQP5WA

**Comment by Tyrrrz** [comment]
Interesting. Looks like that channel isn't accessible by username (or I just can't find a link anywhere). If I ignore the validation and just use the username as is (or url-encoded), YouTube returns 404.

**Comment by Geckon01** [comment]
I've tried some requests with Postman and got 404 too. Also, I've tried get channel uploads and it is not return current live stream. It returns only recorded streams.

**Comment by Tyrrrz** [comment]
Yeah, live streams are not supported.

**Comment by Tyrrrz** [comment]
I've looked into it again and it seems that usernames must indeed contain only latin characters. Note, this is the username that the user registers with, not necessarily their display name. I don't think there's any way to get channel ID from display name.

**Comment by Geckon01** [comment]
I've tried  some dirty hack - you can first use SearchVideosAsync and then get channel id from video with GetVideoAuthorChannelAsync. Something like this:

```
var videoSearchResult = await _youtubeService.SearchVideosAsync(query, 1);
var foundChannel = await _youtubeService.GetVideoAuthorChannelAsync(videoSearchResult[0].Id);
```

I think it's not proper solution, but maybe it'll help someone.

**Comment by Tyrrrz** [comment]
@Geckon01 that's a pretty good solution.
