### ISSUE TITLE
System.FormatException: Input string was not in a correct format.

### ISSUE THREAD

**Issue by WeepingBoil** [Tyrrrz/YoutubeExplode#380]
Error https://www.youtube.com/watch?v=EqzzbZ0M3HU

System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at System.Xml.Linq.XAttribute.op_Explicit(XAttribute attribute)
   at YoutubeExplode.ReverseEngineering.Responses.DashManifest.StreamInfo.GetTag()
   at YoutubeExplode.Videos.Streams.StreamsClient.<GetManifestAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at YoutubeExplode.Videos.Streams.StreamsClient.<GetManifestAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()

**Comment by WeepingBoil** [comment]
...because it was a live stream perhaps?

**Comment by Tyrrrz** [comment]
For some reason, all streams returned for this video seem broken. Not sure why.

**Comment by Tyrrrz** [comment]
It doesn't throw exceptions anymore but the list of streams is empty because all of them are broken somehow (even though it plays in a browser).
