### ISSUE TITLE
Video download In 720p failed (stream URL not playable)

### ISSUE THREAD

**Issue by ALSULTAN** [Tyrrrz/YoutubeExplode#388]
Failed: System.IO.IOException: Received an unexpected EOF or 0 bytes from the transport stream.
   at System.Net.ConnectStream.EndRead(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrimPromise`1.Complete(TInstance thisRef, Func`3 endMethod, IAsyncResult asyncResult, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClientHandler.WebExceptionWrapperStream.<ReadAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()

**Comment by ALSULTAN** [comment]
this is the video URL: https://www.youtube.com/watch?v=6hfBeSiLJLU

And here is the stream URL:
https://r5---sn-nuj-g0iz.googlevideo.com/videoplayback?expire=1591072311&ei=1oHVXr6aPMmZ1wbDr5-oAg&ip=95.185.202.223&id=o-ALTfh3p2EPzVSNtsrW8TEueK_CJ3ETwUsCfEfx4Hk5L7&itag=22&source=youtube&requiressl=yes&mh=Yl&mm=31%2C29&mn=sn-nuj-g0iz%2Csn-hgn7rn7k&ms=au%2Crdu&mv=m&mvi=4&pl=24&initcwndbps=376250&vprv=1&mime=video%2Fmp4&ratebypass=yes&dur=2547.623&lmt=1559942950764197&mt=1591050635&fvip=5&c=WEB&txp=5535432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAIpQVbGFBk88BT4YZYefROtOrxkHm7ImGXwX4dlXr16rAiEAiRBdgs7oQMiRznfgmS8jDe_iDYRbc8qm9qIoo_xG3EY%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgZHhyU_ExwOAYIh0iflul4JJ7v_9ewg14ny1_w1YjbC0CIEWbrTT2XNastLhJIEay6ws7YLh1Abu8VmjhWPrZNMrI

**Comment by Tyrrrz** [comment]
Honestly, errors like this are evidence of an issue on YouTube's side. You're probably better of trying to handle such exceptions in your code and falling back to other streams or providing an error message.
