### ISSUE TITLE
Streams of age restricted videos are not available anymore.

### ISSUE THREAD

**Issue by Hexer10** [Tyrrrz/YoutubeExplode#394]
The test `I_can_get_a_specific_stream_of_any_playable_YouTube_video` fails on `SkRSXFQerZs`, with the given stacktrace:
```
YoutubeExplode.Tests.StreamsSpecs.I can get a specific stream of any playable YouTube video(videoId: "SkRSXFQerZs")

YoutubeExplode.Exceptions.VideoUnplayableException : Video 'SkRSXFQerZs' is unplayable.
Streams are not available for this video.
In most cases, this error indicates that there are some restrictions in place that prevent watching this video.

Reason:
   at YoutubeExplode.Videos.Streams.StreamsClient.GetStreamContextFromWatchPageAsync(VideoId videoId) in D:\RiderProjects\YoutubeExplode\YoutubeExplode\Videos\Streams\StreamsClient.cs:line 91
   at YoutubeExplode.Videos.Streams.StreamsClient.GetManifestAsync(VideoId videoId) in D:\RiderProjects\YoutubeExplode\YoutubeExplode\Videos\Streams\StreamsClient.cs:line 255
   at YoutubeExplode.Tests.StreamsSpecs.I_can_get_a_specific_stream_of_any_playable_YouTube_video(String videoId) in D:\RiderProjects\YoutubeExplode\YoutubeExplode.Tests\StreamsSpecs.cs:line 93
--- End of stack trace from previous location where exception was thrown ---

```
If you try to open the embed page from the browser you can see that it does not work anymore but says that the `Video unavailable`.

**Comment by Tyrrrz** [comment]
>If you try to open the embed page from the browser you can see that it does not work anymore but says that the Video unavailable.

If that is the case, it's likely YouTube finally closed that loophole.
