### ISSUE TITLE
Signature deciphering: forbidden error

### ISSUE THREAD

**Issue by vsjtechnologies** [Tyrrrz/YoutubeExplode#437]
Method: GET, RequestUri: 'https://r5---sn-aigzrn76.googlevideo.com/videoplayback/expire/1599578365/ei/nUxXX4LRFunmxN8Pvc2ZgAQ/ip/82.223.36.215/id/725e5c3c9d5ddc55/itag/251/source/youtube/requiressl/yes/mh/73/mm/31,26/mn/sn-aigzrn76,sn-4g5e6nz7/ms/au,onr/mv/u/mvi/5/pl/25/vprv/1/ratebypass/yes/mime/audio/webm/otfp/1/gir/yes/clen/59274575/lmt/1599489111272519/dur/3794.961/mt/1599556583/fvip/5/keepalive/yes/sparams/expire,ei,ip,id,itag,source,requiressl,vprv,ratebypass,mime,otfp,gir,clen,lmt,dur/sig/AOq0QJ8wRQIget47HySsVupt8JZ40zg-8gDCEVRpZRJktkUv5GuRgtUCIQDNJe_cIbtX4P8aAo82BDIxk_lY_dMI977vP6lTjsmliA==/lsparams/mh,mm,mn,ms,mv,mvi,pl/lsig/AG3C_xAwRAIgd8H407FQQJEusFbNlGUeUeMyFdLJwad-Vb30Q3VsATcCIHUxU6gNK8KFhsh0jKvjFcqltAKEtD6hIqH9gVCGnftH/', Version: 1.1, Content: <null>, Headers:
{
  Range: bytes=0-9223372036854775806
  User-Agent: Mozilla/5.0
  User-Agent: (Windows NT 10.0; Win64; x64)
  User-Agent: AppleWebKit/537.36
  User-Agent: (KHTML, like Gecko)
  User-Agent: Chrome/80.0.3987.163
  User-Agent: Safari/537.36
}

StatusCode: 403, ReasonPhrase: 'Forbidden', Version: 1.1, Content: System.Net.Http.StreamContent, Headers:
{
  Connection: close
  Vary: Origin
  X-Content-Type-Options: nosniff
  Date: Tue, 08 Sep 2020 09:19:29 GMT
  Server: gvs
  Server: 1.0
  Content-Length: 0
  Content-Type: text/plain
  Last-Modified: Wed, 02 May 2007 10:26:10 GMT
}
   at YoutubeExplode.ReverseEngineering.YoutubeHttpClient.CheckResponse(HttpResponseMessage response)
   at YoutubeExplode.ReverseEngineering.YoutubeHttpClient.<GetStreamAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at YoutubeExplode.Internal.SegmentedHttpStream.<ReadAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.IO.Extensions.<ReadAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at YoutubeExplode.Internal.Extensions.StreamExtensions.<CopyBufferedToAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at YoutubeExplode.Internal.Extensions.StreamExtensions.<CopyToAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at YoutubeExplode.Videos.Streams.StreamsClient.<CopyToAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at YoutubeExplode.Videos.Streams.StreamsClient.<DownloadAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at vsj.VsjService.<downloadYoutube>d__9.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at vsj.VsjService.CreateShortURL(String integrationKey, String publicUrl, Boolean createYtbMP3Stream)
---> (Inner Exception #0) YoutubeExplode.Exceptions.FatalFailureException: Failed to perform an HTTP request to YouTube due to a fatal failure.
In most cases, this error indicates that YouTube most likely changed something, which broke the library.
If this issue persists, please report it on the project's GitHub page.

**Comment by Tyrrrz** [comment]
Is this consistent?

**Comment by vsjtechnologies** [comment]
Yes, is consistent since 2 or 3 weeks ago.

**Comment by vinayak-vc** [comment]
https://www.youtube.com/watch?v=uZDYGb7Xh_c

This video won't play because of the Signature cipher.

I am using Unity 2019.4.8f1.

`"{  "itag": 18,  "mimeType": "video/mp4; codecs="avc1.42001E, mp4a.40.2"",  "bitrate": 465509,  "width": 640,  "height": 360,  "lastModified": "1505461863494267",  "contentLength": "6451966",  "quality": "medium",  "fps": 25,  "qualityLabel": "360p",  "projectionType": "RECTANGULAR",  "averageBitrate": 465241,  "audioQuality": "AUDIO_QUALITY_LOW",  "approxDurationMs": "110944",  "audioSampleRate": "44100",  "audioChannels": 2,  "signatureCipher": "s=AOq0QJ8wRgIhANrWphOW_HynnD-3J74_yX9qlZMweY2EsX7Yg4LsuJCYAiEA3Xi2wthCXlMKcl9tocONlbTQFYlX%3Dq4naryyuDDNgPQG&sp=sig&url=https://r4---sn-gwpa-5hqk.googlevideo.com/videoplayback%3Fexpire%3D1602695562%26ei%3DKt2GX6WTHeWx1Abb9q_4Cw%26ip%3D2409%253A4041%253A2e89%253A80ac%253A9cc5%253A8c0d%253A9ca1%253Aa3e8%26id%3Do-AFczLFfE6DZqnCxenfespqi8RvN-6ZSCotOuFPPOMvap%26itag%3D18%26source%3Dyoutube%26requiressl%3Dyes%26mh%3D51%26mm%3D31%252C29%26mn%3Dsn-gwpa-5hqk%252Csn-gwpa-cvhy%26ms%3Dau%252Crdu%26mv%3Dm%26mvi%3D4%26pl%3D36%26initcwndbps%3D190000%26vprv%3D1%26mime%3Dvideo%252Fmp4%26gir%3Dyes%26clen%3D6451966%26ratebypass%3Dyes%26dur%3D110.944%26lmt%3D1505461863494267%26mt%3D1602673849%26fvip%3D4%26fexp%3D23915654%26c%3DWEB%26sparams%3Dexpire%252Cei%252Cip%252Cid%252Citag%252Csource%252Crequiressl%252Cvprv%252Cmime%252Cgir%252Cclen%252Cratebypass%252Cdur%252Clmt%26lsparams%3Dmh%252Cmm%252Cmn%252Cms%252Cmv%252Cmvi%252Cpl%252Cinitcwndbps%26lsig%3DAG3C_xAwRgIhAPsbOzwhlV1VdXewkCZcTXfcr3l85c2iESKOPlGaH7A_AiEAvMdiZ07c9yY8e75nGR696cLrjnWPfa_vDYgPtSeYE1A%253D"}"`

**Comment by Tyrrrz** [comment]
Make sure you're on the latest version.

**Comment by vinayak-vc** [comment]
New Version worked Thanks!!!

I am using this [https://github.com/iBicha/UnityYoutubePlayer](https://github.com/iBicha/UnityYoutubePlayer)

**Comment by Tyrrrz** [comment]
@vsjtechnologies still happening on latest versions?

**Comment by vsjtechnologies** [comment]
With the latest version we do not have this issue. Continue testing.
Thanks !
