### ISSUE TITLE
Error when calling GetManifestAsync

### ISSUE THREAD

**Issue by Chris38** [Tyrrrz/YoutubeExplode#455]
Hello I got a Issue when I try to get the Manifest (Videos.Streams.GetManifestAsync(url)

YoutubeExplode.Exceptions.TransientFailureException
  HResult=0x80131500
  Message=Video watch page is broken.
In most cases, this error indicates that the problem is on YouTube's side and this is not a bug in the library.
To resolve this error, please wait some time and try again.
If this issue persists, please report it on the project's GitHub page.
  Source=YoutubeExplode
  StackTrace:
   at YoutubeExplode.ReverseEngineering.Responses.WatchPage.<>c__DisplayClass9_0.<<GetAsync>b__0>d.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at YoutubeExplode.Internal.Retry.<WrapAsync>d__1`1.MoveNext()
   at YoutubeExplode.Internal.Retry.<WrapAsync>d__1`1.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at YoutubeExplode.ReverseEngineering.Responses.WatchPage.<GetAsync>d__9.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at YoutubeExplode.Videos.Streams.StreamClient.<GetStreamContextFromWatchPageAsync>d__4.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at YoutubeExplode.Videos.Streams.StreamClient.<GetManifestAsync>d__6.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PresentationLayer.SearchSong.<getAllToInfos>d__41.MoveNext() in D:\PlaylistGenerator DatabaseV4.0\PlaylistGeneratorSQLITE\PresentationLayer\SearchSong.xaml.cs:line 482
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PresentationLayer.SearchSong.<lstFound_SelectionChanged_1>d__23.MoveNext() in D:\PlaylistGenerator DatabaseV4.0\PlaylistGeneratorSQLITE\PresentationLayer\SearchSong.xaml.cs:line 131

Could you help me?
Thank you in advance

**Comment by Tyrrrz** [comment]
Does it persist after retrying in a few hours?

**Comment by Chris38** [comment]
Yes, I've been trying for a few days but always the same.

________________________________
Von: Alexey Golub <notifications@github.com>
Gesendet: Mittwoch, 14. Oktober 2020 14:11
An: Tyrrrz/YoutubeExplode <YoutubeExplode@noreply.github.com>
Cc: Chris38 <illuminaten64@hotmail.com>; Author <author@noreply.github.com>
Betreff: Re: [Tyrrrz/YoutubeExplode] Error when calling GetManifestAsync (#455)


Does it persist after retrying in a few hours?

**Comment by rpm61** [comment]
We have been getting this error too. Any update?
