### ISSUE TITLE
Having an issue downloading a fully playable video?

### ISSUE THREAD

**Issue by Montegro** [Tyrrrz/YoutubeExplode#456]
Video ID: -N6h_P-zdog

```
Exception is:
YoutubeExplode.Exceptions.VideoUnplayableException: Video '-N6h_P-zdog' is unplayable.
Streams are not available for this video.
In most cases, this error indicates that there are some restrictions in place that prevent watching this video.

Reason:
   at YoutubeExplode.Videos.Streams.StreamsClient.<GetStreamContextFromWatchPageAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at YoutubeExplode.Videos.Streams.StreamsClient.<GetManifestAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Starship_Tube_Loader.StarshipTubeLoader.<Download_Video>d__44.MoveNext()
```

Unsure of what the reason for this one being unfetchable might be, but it's a video thats been up for a little over a day, and doesn't seem to have any adult flags anywhere...

**Comment by Tyrrrz** [comment]
It appears to work for me.

![image](https://user-images.githubusercontent.com/1935960/96120572-63dbeb00-0ef7-11eb-9d21-43c32b99a6a4.png)

**Comment by Montegro** [comment]
Sorry, I didn't mean to specify during the fetch process, but the download process immediately fails on my end, does the same happen for you?

**Comment by Tyrrrz** [comment]
The download works fine too.

**Comment by Montegro** [comment]
I don't think they split America up by state, do they? If so then I suppose that could be it then...

**Comment by Tyrrrz** [comment]
Maybe #159 will help with this.

**Comment by Montegro** [comment]
Potentially, I'll now be watching that one for progress, thank you for your time
