### ISSUE TITLE
KeyNotFoundException: The given key was not present in the dictionary

### ISSUE THREAD

**Issue by zjjohncq** [Tyrrrz/YoutubeExplode#461]
Today when we download for several videos, we got the exception as
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Text.Json.JsonElement.GetProperty(String propertyName)
   at YoutubeExplode.ReverseEngineering.Responses.WatchPage.PlayerConfig.GetPlayerSourceUrl()
   at YoutubeExplode.Videos.Streams.StreamClient.<GetStreamContextFromWatchPageAsync>d__4.MoveNext()

the video id we tried are:
UHvno7500aM
KBBRMLuOIG4
soiMnWnHyUc
TVw5fXGYfGE
O3XumWlFkQg

my youtubeExplode version is 5.1.7

**Comment by romidi** [comment]
have the same issue

**Comment by eggeggss** [comment]
have the same issue

**Comment by Jack-Paul** [comment]
Having same issue, please resolve it

**Comment by jaywebster18** [comment]
same issue :(

**Comment by GuusStavo38** [comment]
Me too, for all the YouTube links that I use
