### ISSUE TITLE
VideoRequiresPurchaseException no longer thrown for purchase-restricted videos

### ISSUE THREAD

**Issue by Tyrrrz** [Tyrrrz/YoutubeExplode#468]
As seen in latest test runs: https://github.com/Tyrrrz/YoutubeExplode/runs/1315537769

```
Test Run Failed.
Error: I cannot get available streams of a YouTube video that requires purchase(videoId: "p3dDcKOFXQg"): Assert.Throws() Failure
  X I cannot get available streams of a YouTube video that requires purchase(videoId: "p3dDcKOFXQg") [1s 359ms]
  Error Message:
   Assert.Throws() Failure
Expected: typeof(YoutubeExplode.Exceptions.VideoRequiresPurchaseException)
Actual:   typeof(YoutubeExplode.Exceptions.VideoUnplayableException): Video 'p3dDcKOFXQg' is unplayable.
Streams are not available for this video.
In most cases, this error indicates that there are some restrictions in place that prevent watching this video.

Reason: This video requires payment to watch.
---- YoutubeExplode.Exceptions.VideoUnplayableException : Video 'p3dDcKOFXQg' is unplayable.
Streams are not available for this video.
In most cases, this error indicates that there are some restrictions in place that prevent watching this video.

Reason: This video requires payment to watch.
  Stack Trace:
     at YoutubeExplode.Videos.Streams.StreamClient.GetStreamContextFromWatchPageAsync(VideoId videoId) in D:\a\YoutubeExplode\YoutubeExplode\YoutubeExplode\Videos\Streams\StreamClient.cs:line 107
   at YoutubeExplode.Videos.Streams.StreamClient.GetManifestAsync(VideoId videoId) in D:\a\YoutubeExplode\YoutubeExplode\YoutubeExplode\Videos\Streams\StreamClient.cs:line 260
----- Inner Stack Trace -----
   at YoutubeExplode.Videos.Streams.StreamClient.GetStreamContextFromWatchPageAsync(VideoId videoId) in D:\a\YoutubeExplode\YoutubeExplode\YoutubeExplode\Videos\Streams\StreamClient.cs:line 107
   at YoutubeExplode.Videos.Streams.StreamClient.GetManifestAsync(VideoId videoId) in D:\a\YoutubeExplode\YoutubeExplode\YoutubeExplode\Videos\Streams\StreamClient.cs:line 260
```

Looks like YouTube changed something and we are no longer able to extract preview video ID to throw a more specific exception.

**Comment by jratnani20** [comment]
hey @Adegitetaiwo i am intrested in this, can you please assign task to me.....thnks in advnc

**Comment by Hexer10** [comment]
I'm not sure why, but in my port of Dart this still works correctly:
```
  var yt = YoutubeExplode();
  var x = await yt.videos.streamsClient.getManifest(VideoId('p3dDcKOFXQg')); //Here throws VideoRequiresPurchaseException
  print(x);
```

**Comment by Tyrrrz** [comment]
![image](https://user-images.githubusercontent.com/1935960/97786440-47f16e00-1bb4-11eb-9b20-ea82556f134c.png)

Ok, it seems it's just inconsistent. Usually this indicates that YouTube is doing A/B roll out of some new feature, which may be breaking this code.

**Comment by Gabo-7** [comment]
Hello, @Tyrrrz ! I can no longer stream youtube videos with your library, I presume it's because of this issue. Is there any way around Youtube's change? I have a school project that depends on your library and I'm about to panic haha.

**Comment by Tyrrrz** [comment]
Looks like it started working again a while ago. Seems like YouTube reverted that change.
