### ISSUE TITLE
Download Video Exception

### ISSUE THREAD

**Issue by Liuhuifeng** [Tyrrrz/YoutubeExplode#471]
Mvc.ExceptionHandling.AbpExceptionFilter - Video 'Hz18hnsaTzg' is unplayable.
Streams are not available for this video.^M
In most cases, this error indicates that there are some restrictions in place that prevent watching this video.^M
^M
Reason: This live event will begin in 9 hours.
YoutubeExplode.Exceptions.VideoUnplayableException: Video 'Hz18hnsaTzg' is unplayable.^M
Streams are not available for this video.^M
In most cases, this error indicates that there are some restrictions in place that prevent watching this video.^M
^M
Reason: This live event will begin in 9 hours.
   at YoutubeExplode.Videos.Streams.StreamClient.GetStreamContextFromWatchPageAsync(VideoId videoId)
   at YoutubeExplode.Videos.Streams.StreamClient.GetManifestAsync(VideoId videoId)

**Comment by Liuhuifeng** [comment]
sorry. fixed!
