### ISSUE TITLE
Fatal Exception 410 Status

### ISSUE THREAD

**Issue by Martymoose98** [Tyrrrz/YoutubeExplode#587]
### Version

6.0.0-alpha2

### Details

YoutubeExplode.Exceptions.FatalFailureException: Failed to perform an HTTP request to YouTube due to a fatal failure.
In most cases, this error indicates that YouTube most likely changed something, which broke the library.
If this issue persists, please report it on the project's GitHub page.

Method: GET, RequestUri: 'https://www.youtube.com/get_video_info?video_id=dWXpG266ybM&el=embedded&eurl=https:%2F%2Fyoutube.googleapis.com%2Fv%2FdWXpG266ybM&hl=en&sts', Version: 1.1, Content: <null>, Headers:
{
  User-Agent: Mozilla/5.0
  User-Agent: (Windows NT 10.0; Win64; x64)
  User-Agent: AppleWebKit/537.36
  User-Agent: (KHTML, like Gecko)
  User-Agent: Chrome/86.0.4240.111
  User-Agent: Safari/537.36
}

StatusCode: 410, ReasonPhrase: 'Gone', Version: 1.1, Content: System.Net.Http.StreamContent, Headers:
{
  X-Content-Type-Options: nosniff
  X-Frame-Options: SAMEORIGIN
  Strict-Transport-Security: max-age=31536000
  accept-ch: Sec-CH-UA-Arch, Sec-CH-UA-Full-Version, Sec-CH-UA-Model, Sec-CH-UA-Platform, Sec-CH-UA-Platform-Version
  permissions-policy: ch-ua-full-version=*, ch-ua-platform=*, ch-ua-platform-version=*, ch-ua-arch=*, ch-ua-model=*
  X-XSS-Protection: 0
  Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-T051=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
  Cache-Control: public, max-age=86400
  Date: Fri, 10 Sep 2021 13:45:46 GMT
  Server: ESF
  Content-Length: 0
  Content-Type: text/html; charset=utf-8
  Expires: Sat, 11 Sep 2021 13:45:46 GMT
}
   at YoutubeExplode.ReverseEngineering.YoutubeHttpClient.CheckResponse(HttpResponseMessage response)
   at YoutubeExplode.ReverseEngineering.YoutubeHttpClient.<GetStringAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at YoutubeExplode.ReverseEngineering.Responses.VideoInfoResponse.<>c__DisplayClass10_0.<<GetAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at YoutubeExplode.Internal.Retry.<WrapAsync>d__1`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at YoutubeExplode.Internal.Retry.<WrapAsync>d__1`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at YoutubeExplode.ReverseEngineering.Responses.VideoInfoResponse.<GetAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at YoutubeExplode.Videos.VideoClient.<GetVideoFromWatchPageAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at YoutubeExplode.Videos.VideoClient.<GetAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Brunster.VoiceChannelAudioStreamYouTube.<Preload>d__5.MoveNext() in X:\Documents\Visual Studio 2017\Projects\Brunster\Brunster\Brunster\VoiceChannelAudioStreamYouTube.cs:line 72
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Brunster.SongQueue.<Add>d__41.MoveNext() in X:\Documents\Visual Studio 2017\Projects\Brunster\Brunster\Brunster\SongQueue.cs:line 525
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Brunster.SongQueue.<Add>d__40.MoveNext() in X:\Documents\Visual Studio 2017\Projects\Brunster\Brunster\Brunster\SongQueue.cs:line 514
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Brunster.Modules.Commands.<PlayMusic>d__12.MoveNext() in X:\Documents\Visual Studio 2017\Projects\Brunster\Brunster\Brunster\Modules\Commands.cs:line 345
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.Commands.ModuleClassBuilder.<>c__DisplayClass6_0.<<BuildCommand>g__ExecuteCallback|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.Commands.CommandInfo.<ExecuteInternalAsync>d__45.MoveNext()

### Steps to reproduce

This happens when I use my play command supplying the url as the parameter.
The library works as intended with keywords. I'm not sure if it's on my end or an actual fatal bug.

**Comment by Martymoose98** [comment]
Okay for some reason my nuget was configured horribly and didn't get the 6.0.5 update im going to retest with the new version

**Comment by Martymoose98** [comment]
Yep the new version 6.0.5 fixed it after adapting my source for the slight changes in the api
