### ISSUE TITLE
The response ended prematurely

### ISSUE THREAD

**Issue by qtlin** [Tyrrrz/YoutubeExplode#611]
### Version

current master

### Details

downloading one particular video using demo console fails. youtube-dl and yt-dlp have no problems.

### Steps to reproduce

clone latest,
```
$ cd YoutubeExplode/YoutubeExplode.DemoConsole
$ dotnet run
Enter YouTube video ID or URL: 1mUSrQtj4-k
Downloading stream: 720p / mp4... 0.0%
                                  0.0%
                                  0.1%
...
                                  1.7%
                                  Completed ✓
Unhandled exception. System.IO.IOException: The response ended prematurely, with at least 57729574 additional bytes expected.
   at System.Net.Http.HttpConnection.ContentLengthReadStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
   at YoutubeExplode.Utils.SegmentedHttpStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken) in YoutubeExplode/Utils/SegmentedHttpStream.cs:line 82
   at YoutubeExplode.Utils.Extensions.StreamExtensions.CopyBufferedToAsync(Stream source, Stream destination, Byte[] buffer, CancellationToken cancellationToken) in YoutubeExplode/Utils/Extensions/StreamExtensions.cs:line 16
   at YoutubeExplode.Utils.Extensions.StreamExtensions.CopyToAsync(Stream source, Stream destination, IProgress`1 progress, CancellationToken cancellationToken) in YoutubeExplode/Utils/Extensions/StreamExtensions.cs:line 34
   at YoutubeExplode.Videos.Streams.StreamClient.CopyToAsync(IStreamInfo streamInfo, Stream destination, IProgress`1 progress, CancellationToken cancellationToken) in YoutubeExplode/Videos/Streams/StreamClient.cs:line 256
   at YoutubeExplode.Videos.Streams.StreamClient.DownloadAsync(IStreamInfo streamInfo, String filePath, IProgress`1 progress, CancellationToken cancellationToken) in YoutubeExplode/Videos/Streams/StreamClient.cs:line 269
   at YoutubeExplode.DemoConsole.Program.Main() in YoutubeExplode.DemoConsole/Program.cs:line 43
   at YoutubeExplode.DemoConsole.Program.<Main>()
$ 
```

**Comment by Tyrrrz** [comment]
Worked for me. Must be a transient error on YouTube's side.

![image](https://user-images.githubusercontent.com/1935960/148689743-03a84721-49ec-46e6-a2fe-51cf815233e5.png)

**Comment by qtlin** [comment]
Indeed it works now, AND progress percentage now on one line instead of new line every time as before. Same code. Very puzzled.
Secondly, even if it was something on YouTube's side sensitive for YoutubeExplode, two other tools mentioned hasn't noticed anything at all. May it be an indication of a least a minor problem in YoutubeExplode?

**Comment by Tyrrrz** [comment]
> Secondly, even if it was something on YouTube's side sensitive for YoutubeExplode, two other tools mentioned hasn't noticed anything at all. May it be an indication of a least a minor problem in YoutubeExplode?

Not necessarily, they could be downloading another stream. But ultimately hard to tell without reproducing it first.

**Comment by qtlin** [comment]
Same stream, same IP etc, etc. Unfortunately YoutubeExplode.DemoConsole does not print download URL and thus it wasn't possible to compare it with yt-dlp for example.

**Comment by Tyrrrz** [comment]
> Same stream, same IP etc, etc. Unfortunately YoutubeExplode.DemoConsole does not print download URL and thus it wasn't possible to compare it with yt-dlp for example.

You can manually debug it next time that happens. But in my experience, YouTube does have random failures like that from time to time.

**Comment by qtlin** [comment]
I don't have any debugging tools on Linux and have no idea how to debug dotnet.
Regarding "random failures" - it has been going on for several days and over the course of several days other downloaders had zero problems.
Please let me know If you'd like me to open a DemoConsole enhancement request to print download URL before downloading.

**Comment by Tyrrrz** [comment]
> I don't have any debugging tools on Linux and have no idea how to debug dotnet.

I mean, if you can compile the demo, then you can just add a `Console.WriteLine(streamInfo.Url);` statement somewhere before [this line](https://github.com/Tyrrrz/YoutubeExplode/blob/84fd87e9d5161ddac4dcb1c48a03d014c36bcfa2/YoutubeExplode.DemoConsole/Program.cs#L36).

> Regarding "random failures" - it has been going on for several days and over the course of several days other downloaders had zero problems.

Yeah, but unfortunately we're all working in the dark, considering that none of what we're doing is officially supported by YouTube. Other downloaders may be using different approaches to download videos, but unless their authors tell me what they're doing differently I won't know (even reading source code can be an effortful undertaking, given how complicated these tools tend to be).

**Comment by Tyrrrz** [comment]
Also, if you do figure out what causes this issue, I will be happy to know. But, as it stands, it's quite hard to do anything about something that is not consistently reproducible on a system with as many moving parts as YouTube.
