### ISSUE TITLE
Failure with Assembly Trimming

### ISSUE THREAD

**Issue by mysteryx93** [Tyrrrz/YoutubeExplode#696]
### Version

6.2.10

### Details

When using Assembly Trimming in .NET7, I'm having issues with YouTubeExplode. Has it been tested with Assembly Trimming?  Does it rely on reflection?

```
System.NotSupportedException: The deserialization constructor for type '<>f__AnonymousType6`2[System.String,<>f__AnonymousType1`1[<>f__AnonymousType7`6[System.String,System.String,System.Int32,System.String,System.String,System.Int32]]]' contains parameters with null names. This might happen because the parameter names have been trimmed by the linker. Consider using the source generated serializer instead.
   at System.Text.Json.ThrowHelper.ThrowNotSupportedException_ConstructorContainsNullParameterNames(Type declaringType)
   at System.Text.Json.Serialization.Metadata.ReflectionJsonTypeInfo`1.GetParameterInfoValues()
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo.Configure()
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo.<EnsureConfigured>g__ConfigureLocked|143_0()
   at System.Text.Json.JsonSerializerOptions.GetTypeInfoInternal(Type type, Boolean ensureConfigured, Boolean resolveIfMutable)
   at System.Text.Json.JsonSerializer.GetTypeInfo(JsonSerializerOptions options, Type inputType)
   at System.Text.Json.JsonSerializer.GetTypeInfo[T](JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Serialize[TValue](TValue value, JsonSerializerOptions options)
   at YoutubeExplode.Utils.Json.SerializeToHttpContent[T](T)
   at YoutubeExplode.Videos.VideoController.GetPlayerResponseAsync(VideoId, CancellationToken )
   at YoutubeExplode.Videos.Streams.StreamClient.GetStreamInfosAsync(VideoId, CancellationToken )+MoveNext()
   at YoutubeExplode.Utils.Extensions.AsyncCollectionExtensions.ToListAsync[T](IAsyncEnumerable`1)
   at YoutubeExplode.Utils.Extensions.AsyncCollectionExtensions.ToListAsync[T](IAsyncEnumerable`1)
   at YoutubeExplode.Videos.Streams.StreamClient.GetManifestAsync(VideoId, CancellationToken )
   at HanumanInstitute.Downloads.YouTubeDownloader.QueryStreamInfoAsync(VideoId, CancellationToken )
   at HanumanInstitute.Downloads.DownloadManager.QueryStreamInfoAsync(Uri, CancellationToken )
   at HanumanInstitute.YangDownloader.ViewModels.MainViewModel.<>c__DisplayClass66_0.<<QueryImpl>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at HanumanInstitute.YangDownloader.ViewModels.MainViewModel.TryQueryAsync(Func`1)
```

The error being on an anonymous type, it might be a bit harder to get the flags at the right places. How can I solve this?

### Steps to reproduce

Well... you could take YouTubeDownloader and enable Assembly Trimming on it

**Comment by Tyrrrz** [comment]
No, it hasn't been.

> Well... you could take YouTubeDownloader and enable Assembly Trimming on it

These are not actionable steps to reproduce. Can you give an example `dotnet` command line that fails?

**Comment by Tyrrrz** [comment]
After discussing this with the .NET team, the conclusion is that assembly trimming is not supported. You'd have to disable it for this library.

https://twitter.com/Tyrrrz/status/1637123798045544450

**Comment by mysteryx93** [comment]
Ah it would be really complicated to convert anonymous types to typed classes? ok

it just occurred to me, WPF does not support trimming, but Avalonia11 does

**Comment by Sekoree** [comment]
Worst case you could just create a fork and replace the few anonymous types (I think it's around 5) with something like string literals. It's certainly more complicated than just having it directly in the library but it also makes nativeAOT work for example

**Comment by mysteryx93** [comment]
Rotting your assembly changes the output size (after AOT) from 41.9mb to 42.1mb with framework embedded.

It's working fine now.

I'll just note that this app is a lot heavier than the others in terms of dependencies. Other projects that don't download result in 29mb.
