### ISSUE TITLE
Unable to download video from YouTube

### ISSUE THREAD

**Issue by cnapolit** [Tyrrrz/YoutubeExplode#708]
### Version

6.2.2

### Details

When attempting to download a video after retrieving playlist/video information just fine, an exception is thrown stating the video is unavailable. Two users of the plugin I work on and myself have reported this bug and it seems pretty consistent.

Seems like this version at least has stopped functioning within the past week or so. Might be a change on Youtube's side, especially since this repo and the plugin have been pretty stagnant.

The call (from https://github.com/joyrider3774/PlayniteSound/blob/main/Downloaders/YtDownloader.cs#LL118C26-L118C26):
```C#
await _youtubeClient.Videos.DownloadAsync(song.Id, path, o => o.SetFFmpegPath(_settings.FFmpegPath));
```

A ticket opened for this issue: https://github.com/joyrider3774/PlayniteSound/issues/64

The exception for the corresponding ticket:
Something went wrong when attempting to download from Youtube with Id 'ELkfa-MfEw0' and Path 'notGonnaPostSomeonesPath\AppData\Local\Playnite\ExtraMetadata\Games\9d8a2178-410e-460a-b548-0eab48eefd02\Music Files\EX Fight Security System Upgrade - Maintenance Management (A Hat in Time MOD OST).mp3'
YoutubeExplode.Exceptions.VideoUnavailableException: Video 'ELkfa-MfEw0' is not available.
   at YoutubeExplode.Videos.VideoController.<GetPlayerResponseAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at YoutubeExplode.Videos.Streams.StreamClient.<GetManifestAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at YoutubeExplode.Converter.ConversionExtensions.<DownloadAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at YoutubeExplode.Converter.ConversionExtensions.<DownloadAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PlayniteSounds.Downloaders.YtDownloader.<DownloadSongExplodeAsync>d__13.MoveNext() in D:\a\PlayniteSound

### Steps to reproduce

Invoke `YoutubeClient.Videos.DownloadAsync` method with valid parameters.

**Comment by Tyrrrz** [comment]
Have you tried updating to `6.2.14`? You're using `6.2.2` which is severely outdated.

**Comment by cnapolit** [comment]
Behavior not present for 6.2.14, but is for 6.2.5.
Guess the version I'm using has gone too stale, oh well.

I'd update immediately, but I've had issues with the newer versions of the Explode and FileNotFoundExceptions being thrown about looking for particular versions of Microsoft.Bcl.AsyncInterfaces & System.Text.Json.

That's probably has something to do either with nested dependencies or targeting .NET 4.6.2 when explode targets 7+.
Since that's unrelated, I'll close this ticket.

Thanks for the quick response!

**Comment by cnapolit** [comment]
the following handler is able to resolve my exceptions issue at least
'''C#
AppDomain.CurrentDomain.AssemblyResolve += (sender, args) => {
                if (args.Name.StartsWith("System.Text.Json"))
                {
                    return typeof(JsonSerializer).Assembly;
                }
                return null;
            };
'''

**Comment by Tyrrrz** [comment]
When in doubt, just install those packages from NuGet.

**Comment by cnapolit** [comment]
The build process already grabs YoutubeExplode, System.Text.Json, etc. from nuget via the VS browser and builds/installs with them included. I try to stay on well treaded paths in most circumstances to avoid headaches.

I think the issue might be the main application using a version of System.Text.Json 7.0.0 built into .NET 4.6.2 (and thus no dll file matching the expected name). Then Explode/some service on behalf of Explode attempts to load said version, but can't find the dll, and subsequently blows up.

If I find a more concrete answer or proof, I'll update this ticket for others to see.

**Comment by Tyrrrz** [comment]
> I think the issue might be the main application using a version of System.Text.Json 7.0.0 built into .NET 4.6.2 (and thus no dll file matching the expected name).

Legacy .NET does not include `System.Text.Json` in any of its versions. It might be getting pulled by some of your other packages, but generally the version installed in your actual project takes precedence.

**Comment by pflannery** [comment]
@Tyrrrz I get the same issue as originally posted in this issue but using the latest version 6.2.15. 

```js
Video 'GhOFMaqiAOE' is not available.
at YoutubeExplode.Videos.VideoController.GetPlayerResponseAsync(VideoId videoId, Boolean isEmbedded, CancellationToken cancellationToken) in D:\\a\\YoutubeExplode\\YoutubeExplode\\YoutubeExplode\\Videos\\VideoController.cs:line 89
   at YoutubeExplode.Videos.VideoController.GetPlayerResponseAsync(VideoId videoId, CancellationToken cancellationToken) in D:\\a\\YoutubeExplode\\YoutubeExplode\\YoutubeExplode\\Videos\\VideoController.cs:line 94
   at YoutubeExplode.Videos.Streams.StreamClient.GetManifestAsync(VideoId videoId, CancellationToken cancellationToken) in D:\\a\\YoutubeExplode\\YoutubeExplode\\YoutubeExplode\\Videos\\Streams\\StreamClient.cs:line 191
```

**Comment by Tyrrrz** [comment]
> @Tyrrrz I get the same issue as originally posted in this issue but using the latest version 6.2.15.

This is not related to this issue at all. I tried to pull that video and it worked for me, so might be transient issue.
