### ISSUE TITLE
Cannot get manifest due to `System.FormatException: 'The format of value '' is invalid.'`

### ISSUE THREAD

**Issue by gary-89** [Tyrrrz/YoutubeExplode#725]
### Version

ver 6.3.0

### Details

I am simply trying to follow the Readme.md file but I repeatedly get:
`System.FormatException: 'The format of value '' is invalid.'`  
as soon as I `await youtube.Videos.Streams.GetManifestAsync(videoUrl)`.

What am I missing?

### Steps to reproduce

Simply run the `GetManifestAsync` method and you will get the FormatException:
```csharp
var youtube = new YoutubeClient();  
// Get stream manifest  
var videoUrl = "https://youtube.com/watch?v=u_yIGGhubZs";  
var streamManifest = await youtube.Videos.Streams.GetManifestAsync(videoUrl);
```

**Comment by Tyrrrz** [comment]
Please provide the full stacktrace

**Comment by gary-89** [comment]
Here the full stack trace:
(I also attached a few screenshots)
```json
   at System.Net.Http.Headers.HttpHeaderParser.ParseValue(String value, Object storeValue, Int32& index)
   at System.Net.Http.Headers.HttpHeaders.ParseAndAddValue(HeaderDescriptor descriptor, HeaderStoreItemInfo info, String value)
   at System.Net.Http.Headers.HttpHeaders.Add(HeaderDescriptor descriptor, String value)
   at YoutubeExplode.YoutubeHttpHandler.HandleRequest(HttpRequestMessage request) in /_/YoutubeExplode/YoutubeHttpHandler.cs:line 102
   at YoutubeExplode.YoutubeHttpHandler.<SendAsync>d__5.MoveNext() in /_/YoutubeExplode/YoutubeHttpHandler.cs:line 146
   at System.Net.Http.HttpClient.<<SendAsync>g__Core|83_0>d.MoveNext()
   at YoutubeExplode.Utils.Extensions.HttpExtensions.<HeadAsync>d__1.MoveNext() in /_/YoutubeExplode/Utils/Extensions/HttpExtensions.cs:line 28
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at YoutubeExplode.Utils.Extensions.HttpExtensions.<TryGetContentLengthAsync>d__2.MoveNext() in /_/YoutubeExplode/Utils/Extensions/HttpExtensions.cs:line 41
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()
   at YoutubeExplode.Videos.Streams.StreamClient.<GetStreamInfosAsync>d__5.MoveNext() in /_/YoutubeExplode/Videos/Streams/StreamClient.cs:line 77
   at YoutubeExplode.Videos.Streams.StreamClient.<GetStreamInfosAsync>d__5.System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult(Int16 token)
   at YoutubeExplode.Videos.Streams.StreamClient.<GetStreamInfosAsync>d__6.MoveNext() in /_/YoutubeExplode/Videos/Streams/StreamClient.cs:line 198
   at YoutubeExplode.Videos.Streams.StreamClient.<GetStreamInfosAsync>d__6.MoveNext() in /_/YoutubeExplode/Videos/Streams/StreamClient.cs:line 198
   at YoutubeExplode.Videos.Streams.StreamClient.<GetStreamInfosAsync>d__6.System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult(Int16 token)
   at YoutubeExplode.Utils.Extensions.AsyncCollectionExtensions.<ToListAsync>d__3`1.MoveNext() in /_/YoutubeExplode/Utils/Extensions/AsyncCollectionExtensions.cs:line 48
   at YoutubeExplode.Utils.Extensions.AsyncCollectionExtensions.<ToListAsync>d__3`1.MoveNext() in /_/YoutubeExplode/Utils/Extensions/AsyncCollectionExtensions.cs:line 48
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at YoutubeExplode.Videos.Streams.StreamClient.<GetManifestAsync>d__7.MoveNext() in /_/YoutubeExplode/Videos/Streams/StreamClient.cs:line 223
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at YouTubeVideoDownloaderApp.Program.<Main>d__0.MoveNext() in C:\Users\Matteo\source\repos\YouTubeVideoDownloaderApp\YouTubeVideoDownloaderApp\Program.cs:line 20
   at YouTubeVideoDownloaderApp.Program.<Main>(String[] args)
```

![image](https://github.com/Tyrrrz/YoutubeExplode/assets/4557953/a08d4cfd-2ef5-4a35-a92c-7e47966e7fa7)
![image](https://github.com/Tyrrrz/YoutubeExplode/assets/4557953/04512fdc-b894-4dbf-a09b-3fb9a4762d1a)
![image](https://github.com/Tyrrrz/YoutubeExplode/assets/4557953/b28d64d3-76f2-4a98-9dc2-d91320ab868f)

**Comment by Tyrrrz** [comment]
Thanks, fixed

**Comment by gary-89** [comment]
Great! Thanks a lot for your reactivity and help. 
When the fix will be available?
Out of my curiosity, what was the issue about?

**Comment by Tyrrrz** [comment]
> When the fix will be available?

Now.

> Out of my curiosity, what was the issue about?

It was attempting to insert empty cookie headers for some URLs.
