### ISSUE TITLE
Occasionally streams just dies

### ISSUE THREAD

**Issue by Mrgaton** [Tyrrrz/YoutubeExplode#744]
### Version

6.3.4

### Platform

.Net 7

### Steps to reproduce

![image](https://github.com/Tyrrrz/YoutubeExplode/assets/68958481/23753870-fd20-4eec-9f43-cbcd180d56a1)

### Details

System.IO.IOException: Unable to read data from the transport connection: Se ha forzado la interrupción de una conexión existente por el host remoto..
 ---> System.Net.Sockets.SocketException (10054): Se ha forzado la interrupción de una conexión existente por el host remoto.
   at System.Net.Sockets.NetworkStream.Read(Span`1 buffer)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Read(Span`1 buffer)
   at System.Net.Security.SslStream.EnsureFullTlsFrameAsync[TIOAdapter](CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](Memory`1 buffer, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at System.Net.Security.SslStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.Read(Span`1 buffer)
   at System.Net.Http.HttpConnection.Read(Span`1 destination)
   at System.Net.Http.HttpConnection.ContentLengthReadStream.Read(Span`1 buffer)
   at System.Net.Http.HttpBaseStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at Prose_3._0.VoiceChat.Play(MessageEventArgs args, String url) in C:\Users\Mrgaton\OneDrive\Programas\Programas de CSharp\GatitoDiscordSpammer\Prose 3.0\VoiceChat.cs:line 135

### Checklist

- [X] I have looked through existing issues to make sure that this bug has not been reported before
- [X] I have provided a descriptive title for this issue
- [X] I have made sure that that this bug is reproducible on the latest version of the package
- [X] I have provided all the information needed to reproduce this bug as efficiently as possible
- [ ] I have sponsored this project

**Comment by Tyrrrz** [comment]
Don't use raw `HttpClient` to fetch the stream, use `YoutubeClient`.

**Comment by Mrgaton** [comment]
a yea but i ussualy use this
![image](https://github.com/Tyrrrz/YoutubeExplode/assets/68958481/b6a62c1e-2f1a-405c-8236-471bc23eb826)

and stills same error
![image](https://github.com/Tyrrrz/YoutubeExplode/assets/68958481/4ee0f687-6eb9-448c-8179-bc142c06563d)

**Comment by Mrgaton** [comment]
but i suppose the error stills be the System.Net.Sockets.SocketException (10054): and extreme low download speed but its a music bot so

**Comment by Tyrrrz** [comment]
You should only use `new YoutubeClient().Streams.GetAsync(streamInfo, cancellationToken)`. Other options will not work consistently.

**Comment by Mrgaton** [comment]
![image](https://github.com/Tyrrrz/YoutubeExplode/assets/68958481/bcc2316b-15ef-4e13-b9e0-76aab0454283)
I use this

**Comment by Mrgaton** [comment]
> You should only use `new YoutubeClient().Videos.Streams.GetAsync(streamInfo, cancellationToken)`. Other options will not work consistently.

but i just want audio with highest quality

**Comment by Mrgaton** [comment]
And what should I use to just get good audio?

**Comment by Tyrrrz** [comment]
I already answered above. Read the readme.

**Comment by Mrgaton** [comment]
Ok, the youtube.Videos.Streams.GetAsync works perfect sorry for my dumbness
