### ISSUE TITLE
Getting `System.Net.CookieException` on some requests

### ISSUE THREAD

**Issue by tjvxh** [Tyrrrz/YoutubeExplode#762]
### Version

6.3.11

### Platform

.NET Framework 4.8

### Steps to reproduce

Download any video (I used https://www.youtube.com/watch?v=i8CDxQc_9-E) and this bug is pretty likely.

I used YoutubeExplode.Videos.Video video = await youtube.Videos.GetAsync(input.Text); My code worked perfectly as of a couple days ago and suddenly I got bugs preventing download of any video.

### Details

I think a new Youtube security feature broke something. I tried older versions of YoutubeExplode and encountered the same error. When trying to download any video I get Exception thrown: 'System.Net.CookieException' in mscorlib.dll.

More exception details:

```
System.Net.CookieException: An error occurred when parsing the Cookie header for Uri 'https://www.youtube.com/watch?v=i8CDxQc_9-E&bpctr=9999999999&hl=en'. ---> System.Net.CookieException: The 'Domain'='m.youtube.com' part of the cookie is invalid.
   at System.Net.Cookie.VerifySetDefaults(CookieVariant variant, Uri uri, Boolean isLocalDomain, String localDomain, Boolean set_default, Boolean isThrow)
   at System.Net.CookieContainer.CookieCutter(Uri uri, String headerName, String setCookieHeader, Boolean isThrow)
   --- End of inner exception stack trace ---
   at System.Net.CookieContainer.CookieCutter(Uri uri, String headerName, String setCookieHeader, Boolean isThrow)
   at System.Net.CookieContainer.SetCookies(Uri uri, String cookieHeader)
   at YoutubeExplode.YoutubeHttpHandler.HandleResponse(HttpResponseMessage response) in /_/YoutubeExplode/YoutubeHttpHandler.cs:line 155
   at YoutubeExplode.YoutubeHttpHandler.<SendAsync>d__5.MoveNext() in /_/YoutubeExplode/YoutubeHttpHandler.cs:line 169
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PolyfillExtensions.<GetStringAsync>d__4.MoveNext() in /_1/polyshim/1.9.0/contentFiles/cs/any/PolyShim/Net50/HttpClient.cs:line 95
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at YoutubeExplode.Videos.VideoController.<GetVideoWatchPageAsync>d__4.MoveNext() in /_/YoutubeExplode/Videos/VideoController.cs:line 20
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at YoutubeExplode.Videos.VideoClient.<GetAsync>d__8.MoveNext() in /_/YoutubeExplode/Videos/VideoClient.cs:line 48
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at TCT.ExtractorVideo.<DownloadMediaAs>d__9.MoveNext() in C:\Users\tavek\3D Objects\TCT\ExtractorVideo.cs:line 97
```

### Checklist

- [X] I have looked through existing issues to make sure that this bug has not been reported before
- [X] I have provided a descriptive title for this issue
- [X] I have made sure that this bug is reproducible on the latest version of the package
- [X] I have provided all the information needed to reproduce this bug as efficiently as possible
- [ ] I have sponsored this project

**Comment by minhyentcu** [comment]
I also got the same error:
 An error occurred when parsing the Cookie header for Uri 'https://www.youtube.com/watch?v=GdukQUhPpOQ&bpctr=9999999999&hl=en'

**Comment by mate1213** [comment]
Same in **.net8**

**Comment by YevhenManushkin** [comment]
Same in .net core 3.1

**Comment by mate1213** [comment]
THX @tqk2811 !
I can use this again :D
Great!

**Comment by gcadmes** [comment]
The bug appears to be intermittent, for me at least anyway. Retrying succeeds for me after only the 2nd or 3rd try.

My app is .NET MAUI app, .NET8
