### ISSUE TITLE
YoutubeExplode.Exceptions.YoutubeExplodeException: Channel page is broken. Please try again in a few minutes.

### ISSUE THREAD

**Issue by MistressPlague** [Tyrrrz/YoutubeExplode#793]
### Version

v6.3.16

### Platform

.NET Framework v4.7.2 / Windows 10

### Steps to reproduce

Try to use:
```
var YTClient = new YoutubeClient ();
var channel = await YTClient.Channels.GetAsync("UC_je6fYFlPvswP9doc2JFWg");
```

### Details

YoutubeExplode.Exceptions.YoutubeExplodeException: Channel page is broken. Please try again in a few minutes.
   at YoutubeExplode.Channels.ChannelController.<GetChannelPageAsync>d__2.MoveNext() in /_/YoutubeExplode/Channels/ChannelController.cs:line 30
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at YoutubeExplode.Channels.ChannelController.<GetChannelPageAsync>d__3.MoveNext() in /_/YoutubeExplode/Channels/ChannelController.cs:line 42
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at YoutubeExplode.Channels.ChannelClient.<GetAsync>d__4.MoveNext() in /_/YoutubeExplode/Channels/ChannelClient.cs:line 73
--- End of stack trace from previous location where exception was thrown ---

I confirmed manually the channel page still works, and has og:url in its source.

As for expectations, I don't feel the need this needs filled in, of course I would expect no exception and a returned value.

### Checklist

- [X] I have looked through existing issues to make sure that this bug has not been reported before
- [X] I have provided a descriptive title for this issue
- [X] I have made sure that this bug is reproducible on the latest version of the package
- [X] I have provided all the information needed to reproduce this bug as efficiently as possible
- [ ] I have sponsored this project
- [ ] I have not read any of the above and just checked all the boxes to submit the issue

**Comment by MistressPlague** [comment]
It does. I tested.

**Comment by Tyrrrz** [comment]
I couldn't reproduce the issue with the channel ID you provided

**Comment by Tyrrrz** [comment]
Closing as I can't reproduce and thus investigate.
