### ISSUE TITLE
403 error when calling GetManifestAsync on suicide-restricted videos

### ISSUE THREAD

**Issue by wasd52030** [Tyrrrz/YoutubeExplode#795]
### Version

6.3.16

### Platform

.NET 6.0.423/Windows 11

### Steps to reproduce

```C#
using YoutubeExplode;
using YoutubeExplode.Videos.Streams;

var yt=new YoutubeClient();
var url="https://www.youtube.com/watch?v=4QXCPuwBz2E";

var videotManifest=await yt.Videos.Streams.GetManifestAsync(url);
```

### Details

Expected Behavior: Returns valid StreamManifest
Actual Behavior: HttpRequestException thrown

Complete error repor
```
System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at YoutubeExplode.Videos.Streams.StreamClient.TryGetContentLengthAsync(IStreamData streamData, String url, CancellationToken cancellationToken) in /_/YoutubeExplode/Videos/Streams/StreamClient.cs:line 63
   at YoutubeExplode.Videos.Streams.StreamClient.GetStreamInfosAsync(IEnumerable`1 streamDatas, CancellationToken cancellationToken)+MoveNext() in /_/YoutubeExplode/Videos/Streams/StreamClient.cs:line 114
   at YoutubeExplode.Videos.Streams.StreamClient.GetStreamInfosAsync(IEnumerable`1 streamDatas, CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at YoutubeExplode.Utils.Extensions.AsyncCollectionExtensions.ToListAsync[T](IAsyncEnumerable`1 source) in /_/YoutubeExplode/Utils/Extensions/AsyncCollectionExtensions.cs:line 49
   at YoutubeExplode.Utils.Extensions.AsyncCollectionExtensions.ToListAsync[T](IAsyncEnumerable`1 source) in /_/YoutubeExplode/Utils/Extensions/AsyncCollectionExtensions.cs:line 49
   at YoutubeExplode.Videos.Streams.StreamClient.GetStreamInfosAsync(VideoId videoId, PlayerResponse playerResponse, CancellationToken cancellationToken) in /_/YoutubeExplode/Videos/Streams/StreamClient.cs:line 218
   at YoutubeExplode.Videos.Streams.StreamClient.GetStreamInfosAsync(VideoId videoId, CancellationToken cancellationToken) in /_/YoutubeExplode/Videos/Streams/StreamClient.cs:line 276
   at YoutubeExplode.Videos.Streams.StreamClient.GetManifestAsync(VideoId videoId, CancellationToken cancellationToken) in /_/YoutubeExplode/Videos/Streams/StreamClient.cs:line 292
```

### Checklist

- [X] I have looked through existing issues to make sure that this bug has not been reported before
- [X] I have provided a descriptive title for this issue
- [X] I have made sure that this bug is reproducible on the latest version of the package
- [X] I have provided all the information needed to reproduce this bug as efficiently as possible
- [ ] I have sponsored this project
- [ ] I have not read any of the above and just checked all the boxes to submit the issue

**Comment by wasd52030** [comment]
When I perform a large number of downloads at once, there is a higher probability of occurrences exceeding a certain threshold (greater than 50).

**Comment by Tyrrrz** [comment]
I can definitely see it happening on CI, but I don't have the time to investigate. Any help is welcome.

**Comment by dylansunny** [comment]
I think these Youtube videos need age confirmation. That's why the downloads are not accessible.

**Comment by wasd52030** [comment]
> I think these Youtube videos need age confirmation. That's why the downloads are not accessible.

It displays a similar page
I knew from the start that this video was about suicide, but I just want to listen to the music
![image](https://github.com/Tyrrrz/YoutubeExplode/assets/71220988/4f3153d5-b030-4184-8807-ff01543f7c43)

**Comment by Tyrrrz** [comment]
I had some time to investigate this issue, but unfortunately didn't come up with a solution. However, it seems that the deciphering process did not change and YoutubeExplode still performs that part correctly. My guess is that YouTube added a new form of verification for `TVHTML5` client (that we use for age-restricted videos), but I have not been able to reverse-engineer it yet.

**Comment by vadmium** [comment]
FYI I recently found that if stream URLs have an “n=. . .” query parameter, I have to transform the values or I get 403 responses. The transform function is in the player Java Script. To find the function, look where it is called, just after the `.get("n")` method call. For instance it is the _yma_ function in the following.

```javascript
yma = function(a) {
    var b = a.split("")
    /* . . . */
    return b.join("")
};
/* . . . */
(b = a.get("n"))
    && (b = yRa[0](b),
        a.set("n", b),
        yRa.length || yma(""))
/* . . . */
var yRa = [yma];
```

**Comment by Tyrrrz** [comment]
Thanks @vadmium.

I remember previously the `n` parameter was only responsible for whether the downloads are throttled or not. Is it now required to access the stream altogether?

**Comment by Tyrrrz** [comment]
Another video test case: https://www.youtube.com/watch?v=vcw5THyM7Jo
