### ISSUE TITLE
iso-2022-cn is not a supported encoding name

### ISSUE THREAD

**Issue by Mindrix95** [Tyrrrz/YoutubeExplode#825]
### Version

6.8.1

### Platform

.NET 8.0 / Windows 11

### Steps to reproduce

- Step 1

```C#
public class YoutubeService
{
    YoutubeClient youtubeClient;
    public YoutubeService()
    {
        youtubeClient = new YoutubeClient();
    }
    public async Task<Stream> DownloadVideo(string url)
    {
        var video = await youtubeClient.Videos.GetAsync(url); //Error
        var streamManifest = await youtubeClient.Videos.Streams.GetManifestAsync(video.Url);
        var streamInfo = streamManifest.GetMuxedStreams().GetWithHighestVideoQuality();
        return await youtubeClient.Videos.Streams.GetAsync(streamInfo);
    }
}
```

- Step 2

```C#
string url = "randomUrl"
var stream = await youtubeServices.DownloadVideo(url);
```

### Details

When this line is executed : 

```C#
var video = await youtubeClient.Videos.GetAsync(url);
```

 I get the error : 

`System.ArgumentException : ''iso-2022-cn' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method. Arg_ParamName_Name`

```
   at System.Text.EncodingTable.InternalGetCodePageFromName(String name)
   at System.Text.EncodingTable.GetCodePageFromName(String name)
   at System.Text.Encoding.GetEncoding(String name)
   at AngleSharp.Text.TextEncoding.GetEncoding(String name, Encoding fallback)
```

Don't hesitate to contact me if you need more information.

### Checklist

- [X] I have looked through existing issues to make sure that this bug has not been reported before
- [X] I have provided a descriptive title for this issue
- [X] I have made sure that this bug is reproducible on the latest version of the package
- [X] I have provided all the information needed to reproduce this bug as efficiently as possible
- [ ] I have sponsored this project
- [ ] I have not read any of the above and just checked all the boxes to submit the issue

**Comment by Tyrrrz** [comment]
Interesting. What locale is set on the machine that runs that code?

**Comment by Mindrix95** [comment]
Current locale: ('English_United Kingdom', '1252')

**Comment by Tyrrrz** [comment]
Which video were you fetching?

**Comment by Mindrix95** [comment]
This one for exemple : https://youtu.be/ZdeiaXLug5w?si=zkQyTaRsunZj5FD4

**Comment by Mindrix95** [comment]
![image](https://github.com/user-attachments/assets/0ac138cb-be55-418a-94c8-f32bb6377dae)

**Comment by Tyrrrz** [comment]
It looks like it's just a debug-time exception that you can skip or ignore. I don't know why Visual Studio breaks on it.

That code is inside a `try`/`catch`:

https://github.com/AngleSharp/AngleSharp/blob/5dc976bb0c4b30799e28a0ea43eff180f4259964/src/AngleSharp/Text/TextEncoding.cs#L295-L307

Related issue: https://github.com/AngleSharp/AngleSharp/issues/326
