### ISSUE TITLE
400 Bad request since 26/11/2024

### ISSUE THREAD

**Issue by Skinz3** [Tyrrrz/YoutubeExplode#844]
### Version

6.4.4

### Platform

.NET 7 / Windows server

### Steps to reproduce

System.AggregateException: One or more errors occurred. (Response status code does not indicate success: 400 (Bad Request).)
 ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 400 (Bad Request).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at YoutubeExplode.Videos.VideoController.GetPlayerResponseAsync(VideoId videoId, CancellationToken cancellationToken) in /_/YoutubeExplode/Videos/VideoController.cs:line 97

Hello ! 
This
Just appears since today. I was using youtube explode since a few months without any issue (im passing session cookie)

Its working on my local computer. But i got this error on my server since today.

До біса Росія btw

### Details

Error while getting manifest

My problem appears here : 
`  var streamManifest = await youtube.Videos.Streams.GetManifestAsync(video.Id);
            var streamInfo = streamManifest
    .GetAudioOnlyStreams()
    .MaxBy(x => x.Bitrate);`

**Comment by Abbossbek** [comment]
I have this issue too.

**Comment by UWPDever** [comment]
I have this issue too.

**Comment by Abbossbek** [comment]
Hello,

I appreciate the hard work and dedication you put into maintaining this project. I wanted to bring to your attention a critical issue that has been affecting the functionality of the library since 26/11/2024. The error message "Response status code does not indicate success: 400 (Bad Request)" is causing significant disruptions, particularly on server environments.

Given the widespread impact and the number of users affected, I kindly request that this issue be prioritized for a prompt resolution. Your timely intervention would greatly benefit the community relying on this library.

Thank you for your understanding and support.

**Comment by Ryuchetval** [comment]
I am facing the same issue on a .net 8 / debian server setup with latest version of YouTube Explode 6.5.0 (was happening also on 6.4.3)
With cookies, I get back this error:

System.Net.Http.HttpRequestException: Response status code does not indicate success: 400 (Bad Request).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at YoutubeExplode.Videos.VideoController.GetPlayerResponseAsync(VideoId videoId, CancellationToken cancellationToken) in /_/YoutubeExplode/Videos/VideoController.cs:line 97
   at YoutubeExplode.Videos.Streams.StreamClient.GetStreamInfosAsync(VideoId videoId, CancellationToken cancellationToken) in /_/YoutubeExplode/Videos/Streams/StreamClient.cs:line 258
   at YoutubeExplode.Videos.Streams.StreamClient.GetManifestAsync(VideoId videoId, CancellationToken cancellationToken) in /_/YoutubeExplode/Videos/Streams/StreamClient.cs:line 292


without cookies I get back this error:

YoutubeExplode.Exceptions.VideoUnavailableException: Video 'v_JMkscQuGY' is not available.
   at YoutubeExplode.Videos.VideoController.GetVideoWatchPageAsync(VideoId videoId, CancellationToken cancellationToken) in /_/YoutubeExplode/Videos/VideoController.cs:line 39
   at YoutubeExplode.Videos.VideoClient.GetAsync(VideoId videoId, CancellationToken cancellationToken) in /_/YoutubeExplode/Videos/VideoClient.cs:line 37


From local machine it works properly but not on the server

**Comment by Tyrrrz** [comment]
Do you see this on specific videos? I can't reproduce the issue

**Comment by Abbossbek** [comment]
> Do you see this on specific videos? I can't reproduce the issue

Attempt to download the video using a VPN set to Germany; an error message should appear.

**Comment by Abbossbek** [comment]
![image](https://github.com/user-attachments/assets/4241af56-2bdf-4274-8cb1-3ece7aca2bdf)
All these issues in YoutubeDownloader are related to this. If the error in the library is fixed, these will also be automatically resolved.

**Comment by gcadmes-extron** [comment]
I'm getting this error too. 
Any idea's on how to resolve?

**Comment by Tyrrrz** [comment]
The original issue wasn't clear as to whether this error happens with or without authentication (i.e. cookies), but it appears this is a duplicate of #852
