### ISSUE TITLE
GetUploads exception when one of playlists is unavailable- or something similar 

### ISSUE THREAD

**Issue by tspossible** [Tyrrrz/YoutubeExplode#854]
### Version

6.5.0

### Platform

MacOs

### Steps to reproduce

var channel = await youtube.Channels.GetByHandleAsync("https://www.youtube.com/@wideoprezentacje");
var videosFromChannel = await youtube.Channels.GetUploadsAsync(channel.Id);

### Details

```
YoutubeExplode.Exceptions.PlaylistUnavailableException: Playlist 'UUViVL2aOkLWKcFVi0_p6u6g' is not available.
   at YoutubeExplode.Playlists.PlaylistController.GetPlaylistNextResponseAsync(PlaylistId playlistId, Nullable`1 videoId, Int32 index, String visitorData, CancellationToken cancellationToken) in /_/YoutubeExplode/Playlists/PlaylistController.cs:line 106
   at YoutubeExplode.Playlists.PlaylistClient.GetVideoBatchesAsync(PlaylistId playlistId, CancellationToken cancellationToken)+MoveNext() in /_/YoutubeExplode/Playlists/PlaylistClient.cs:line 86
   at YoutubeExplode.Playlists.PlaylistClient.GetVideoBatchesAsync(PlaylistId playlistId, CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at YoutubeExplode.Utils.Extensions.AsyncCollectionExtensions.SelectManyAsync[TSource,T](IAsyncEnumerable`1 source, Func`2 transform)+MoveNext() in /_/YoutubeExplode/Utils/Extensions/AsyncCollectionExtensions.cs:line 29
   at YoutubeExplode.Utils.Extensions.AsyncCollectionExtensions.SelectManyAsync[TSource,T](IAsyncEnumerable`1 source, Func`2 transform)+MoveNext() in /_/YoutubeExplode/Utils/Extensions/AsyncCollectionExtensions.cs:line 29
   at YoutubeExplode.Utils.Extensions.AsyncCollectionExtensions.SelectManyAsync[TSource,T](IAsyncEnumerable`1 source, Func`2 transform)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at YoutubeExplode.Utils.Extensions.AsyncCollectionExtensions.ToListAsync[T](IAsyncEnumerable`1 source) in /_/YoutubeExplode/Utils/Extensions/AsyncCollectionExtensions.cs:line 49
   at YoutubeExplode.Utils.Extensions.AsyncCollectionExtensions.ToListAsync[T](IAsyncEnumerable`1 source) in /_/YoutubeExplode/Utils/Extensions/AsyncCollectionExtensions.cs:line 49
   at YoutubeExplode.Common.BatchItemExtensions.CollectAsync[T](IAsyncEnumerable`1 source) in /_/YoutubeExplode/Common/IBatchItem.cs:line 30
   at MediaDownloader.Web.Services.DownloaderService.CheckNewVideosForChannel(PerformContext context, Int32 chann
```

### Checklist

- [X] I have looked through existing issues to make sure that this bug has not been reported before
- [X] I have provided a descriptive title for this issue
- [X] I have made sure that this bug is reproducible on the latest version of the package
- [X] I have provided all the information needed to reproduce this bug as efficiently as possible
- [ ] I have sponsored this project
- [ ] I have not read any of the above and just checked all the boxes to submit the issue

**Comment by Tyrrrz** [comment]
Seems to work now
