### ISSUE TITLE
Exception thrown: 'System.ArgumentException' in mscorlib.dll

### ISSUE THREAD

**Issue by Kajirinn** [Tyrrrz/YoutubeExplode#94]
This only occurs for some video's, about 1 - 5% of them. It gives me an ArgumentException for illegal characters.

Example [song ](https://youtu.be/coo0t513Tek)where it occurs.

```
Exception thrown: 'System.ArgumentException' in mscorlib.dll
System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.GetFileName(String path)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at YoutubeExplode.YoutubeClient.<DownloadMediaStreamAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
```

apologies if I'm doing something wrong but I thought I'd make an issue about it regardless.

**Comment by Tyrrrz** [comment]
The issue is exactly what it says it is, you're probably using the video's title as a file name and it has illegal characters.
